import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage();
await p.goto("http://127.0.0.1:4173/?tab=grades&amode=drills");
await p.getByLabel("Поиск по корпусным свёрлам").fill("SD-U");
await p.waitForTimeout(400);
const items = await p.locator(".hb-search-item").allInnerTexts();
console.log("подсказки:", items.slice(0, 6));
await p.locator(".hb-search-item").first().click();
await p.waitForTimeout(300);
const card = await p.getByTestId("body-card").innerText();
console.log("--- карточка:\n" + card.slice(0, 400));
await b.close();
