import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage();
p.on("console", async m => { if (m.type()==="error") console.log("CONSOLE:", m.text().slice(0,1500)); });
await p.goto("http://127.0.0.1:4173/?tab=grades&amode=holders");
await p.getByLabel("Поиск по державкам").fill("MTFNR");
await p.waitForTimeout(400);
await p.locator(".hb-search-item").first().click();
await p.waitForTimeout(800);
await b.close();
